dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-1.2"
if: tag IS blank


jobs:
  include:
    - stage: build and publish
      language: java
      jdk: oraclejdk8
      install: skip
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "Travis CI"
        - git config --local user.email "travis@example.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: 0ccbf69461928c491ad3091e15fb356dffcd3663
        file: "build/libs/pal-tracker.jar"
        skip_cleanup: true
    - stage: deploy to review
      language: bash
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P build/libs https://github.com/manoj79k/pal-tracker/releases/download/$RELEASE_TAG/pal-tracker.jar
      before_deploy:
        - echo "Deploying $RELEASE_TAG to review"
      deploy:
        provider: cloudfoundry
        api: https://api.sys.pikes.pal.pivotal.io
        username: squadri@ford.com
        password: cnyed2xx
        organization: imad-quadri
        space: review
